### ISSUE TITLE
The sdist of pylastfm-0.1.0 is not equivalent to the tree in the repository

### ISSUE THREAD

**Issue by dahlia** [thesquelched/pylastfm#6]
The [sdist of pylastfm-0.1.0][1] uploaded to PyPI is not equivalent to the tree of b1cbe04b9c92a72ca2e29ef538a6719380568627 (which is tagged as 0.1.0) in the repository.

For example, setup.py in the sdist consists of 61 lines, while the same file in the tree of b1cbe04b9c92a72ca2e29ef538a6719380568627 consists of just 28 lines.

[1]: https://pypi.python.org/packages/source/p/pylastfm/pylastfm-0.1.0.tar.gz#md5=576dbe25f32a5b1502a941f26030db04

**Comment by thesquelched** [comment]
Sorry this has taken me so long to look at, but I've been busy with a new baby.  I'll try to get this fixed ASAP.
